version: 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
install:
- ps: >-
    # Install MonoGame

    Write-Host ("Installing MonoGame...")

    (New-Object Net.WebClient).DownloadFile('http://www.monogame.net/releases/v3.6/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')

    Start-Process -FilePath "C:\MonoGameSetup.exe" -ArgumentList "/S /v /qn"

    # Make sure all dependencies are fully installed

    Start-Sleep -s 5
before_build:
- cmd: nuget restore
build:
  project: ProjectRift.sln
  verbosity: minimal
test_script:
- ps: >-
    nunit3-console ProjectRift.Test\bin\Debug\ProjectRift.Test.dll --result=myresults.xml

    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH

    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh

    bash codecov.sh -f "myresults.xml" -t f5a18a4a-89ac-4889-8d39-c587f23952ec

    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\myresults.xml))
artifacts:
- path: ProjectRift\bin\DesktopGL\AnyCPU\Debug\*
  name: Binaries (Debug)
- path: ProjectRift\bin\DesktopGL\AnyCPU\Release\*
  name: Binaries