version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: >-
    # Install MonoGame

    Write-Host ("Installing MonoGame...")

    (New-Object Net.WebClient).DownloadFile('http://www.monogame.net/releases/v3.6/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')

    Start-Process -FilePath "C:\MonoGameSetup.exe" -ArgumentList "/S /v /qn"

    # Make sure all dependencies are fully installed

    Start-Sleep -s 5
before_build:
- cmd: nuget restore
build:
  verbosity: normal
artifacts:
- path: ProjectRift\bin\DesktopGL\AnyCPU\Release\*
  name: Binaries